### ISSUE TITLE
Checkout negative Quantity

### ISSUE THREAD

**Issue by bostonsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#1]
When selecting the amount of tickets I wanted to buy, I clicked the - when I was at 1 and the whole checkout process disappeared

Screen recording - https://share.getcloudapp.com/xQub7Wnq

**Comment by RobertUpchurch** [comment]
Is it wanted to be able to remove the items from the cart?

if yes, I will make a your cart is empty screen.
if no, I will make it so you cannot remove the 1st ticket

We can also do both in separate buttons?

**Comment by bostonsiliconslopes** [comment]
Well if you make the cart is empty, how would they add the ticket again if it was by accident?

I say we make it so you cannot remove the 1st ticket, if they dont want to buy it then they can exit the site.
