### ISSUE TITLE
Suggestion: Have somewhere to see how many tickets I have purchased through my account

### ISSUE THREAD

**Issue by emsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#10]

**Comment by RobertUpchurch** [comment]
Please be more descriptive and we can put this into the conversation for V2

**Comment by emsiliconslopes** [comment]
I bought 4 tickets and then I bought another 2 on a separate transaction. It would be great to be able to reference how many tickets I have bought all together and for whom.
