### ISSUE TITLE
Needs Favicon

### ISSUE THREAD

**Issue by RobertUpchurch** [AxiaLabs/SiliconSlopes-IssueTracker#11]
The browser tab has the universal favicon because we dont have one in the repository. We need to grab one from somewhere or make one

**Comment by bostonsiliconslopes** [comment]
![SS White Logo](https://user-images.githubusercontent.com/82671828/115066071-3ecb3380-9eac-11eb-8aac-c53fde6f0d15.png)

I would like to use this as the favicon, but idk where we need to store it
