### ISSUE TITLE
Deactivate Account Option not available in phase 1

### ISSUE THREAD

**Issue by djoaks** [AxiaLabs/SiliconSlopes-IssueTracker#12]
There is an option on the https://dev.dashboard.siliconslopes.com/account/user/account page to "Deactivate your account." Although clicking on it generates a popup and messaging that indicates the deactivation has occurred, no API for this functionality is in play, and nothing is actually 
<img width="996" alt="Screen Shot 2021-04-16 at 12 01 48 PM" src="https://user-images.githubusercontent.com/82674218/115066663-1a238b80-9ead-11eb-8b72-8eba14b6415c.png">
happening at the database level.

**Comment by RobertUpchurch** [comment]
Good Point. Do we want to remove this section or we can replace the modal with info on who to email for deactivation. 

This is required by GDPR but we are not in the EU so it can be removed I believe without legal problems for now. Many integrations require you to have GDPR compliance but V1 integrates only with Omnicore

**Comment by bostonsiliconslopes** [comment]
@RobertUpchurch @djoaks Is it okay if we direct users to email helpdesk@siliconslopes.com if they want to deactivate their account?

**Comment by RobertUpchurch** [comment]
Yes will do
