### ISSUE TITLE
Specify email vs text to confirm account

### ISSUE THREAD

**Issue by emmasiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#14]
When I was creating my account, after inputting my phone number and email address I was expecting to get a text message to confirm my account, but it came as an email instead. It would be nice to have it specified in the dialogue box to check for an email that will confirm your account.

**Comment by RobertUpchurch** [comment]
![Screen Shot 2021-04-16 at 2 50 16 PM](https://user-images.githubusercontent.com/39099041/115082380-11d64b00-9ec3-11eb-94a0-a4d5a7bc8b9d.png)
This is currently the message you receive for 2FA. Do we need to leave it up longer or are you suggesting putting this somewhere else?

**Comment by bostonsiliconslopes** [comment]
I think we stick with what it is now.
