### ISSUE TITLE
Data Validation: CreateOrder API Submission is incomplete

### ISSUE THREAD

**Issue by djoaks** [AxiaLabs/SiliconSlopes-IssueTracker#16]
2 Issues:
The API request doesn't include the line item for “CustomerOrderPaymentMethodCustomerID” This is the Stripe Customer ID. 

Also, the line item "CustomerOrderPaymentConfirmation" should read "CustomerOrderPaymentConfirmationID" (add ID at the end). These values aren't being captured in the database.

![Screen Shot 2021-04-16 at 2 42 51 PM](https://user-images.githubusercontent.com/82674218/115082301-efdcc880-9ec2-11eb-8044-dadf3263d7d8.png)

**Comment by RobertUpchurch** [comment]
Is support for the CustomerOrderPaymentMethodCustomerID ready? I can add it in but it will need to be returned by readCustomer or it will always generate a new customer on every purchase

**Comment by djoaks** [comment]
The CustomerOrderPaymentMethodCustomerID is populating in the database when submitted. Rather than changing the ReadCustomer, we will prioritize getting you a ReadCustomerPaymentMethods API.

**Comment by RobertUpchurch** [comment]
Ok im pushing the bug fix but I havent turned on the StipeCustomerCreation flow until we get that part worked out
