### ISSUE TITLE
Heading Changes - start madness page

### ISSUE THREAD

**Issue by demitrih** [AxiaLabs/SiliconSlopes-IssueTracker#17]
![image](https://user-images.githubusercontent.com/34491406/116431823-5cca5980-a805-11eb-9b9b-bacf1dd05a5c.png)
1. change title to h1 

![image](https://user-images.githubusercontent.com/34491406/116431857-6489fe00-a805-11eb-8752-b13c57516f06.png)
2. Change form headings to h2 (semibold titles) 

![image](https://user-images.githubusercontent.com/34491406/116431898-6e136600-a805-11eb-8df2-69794d5a8b6e.png)
3. change navigation buttons to Uppercase, wide kerning (similar to subscribe button) 

4. Reduce form padding on mobile

**Comment by RobertUpchurch** [comment]
Finished
