### ISSUE TITLE
Founder’s Hub Origins- filler text underneath

### ISSUE THREAD

**Issue by emsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#19]
Under the Founder’s Hub Origins heading, there is filler text in the body. 
[](https://foundershub.ceo.com/about)

**Comment by emmasiliconslopes** [comment]
Worked with Boston and Em to re-write this. 

Change the title from "Founder's Hub Origins" to "Founder's Hub Beta"

The paragraph should say: 

There are big plans in sight for Founder’s Hub. We are committed to constant improvement and are excited to build a tight-knit community. This beta version launches the beginning of a journey that will take founders, entrepreneurs, and CEOs to new heights. In the future, Founder’s Hub will provide startups with a profile and platform - a one-stop shop - to share company information, enter into startup competitions, and find investors. It might seem good now, but the best is yet to come.
