### ISSUE TITLE
Under 'StartMadness Stats' heading, filler text underneath 

### ISSUE THREAD

**Issue by emsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#21]
<img width="1255" alt="Screen Shot 2021-04-28 at 11 16 33 AM" src="https://user-images.githubusercontent.com/82673388/116445505-314e6b80-a813-11eb-9868-a1ff20cefef5.png">

**Comment by emmasiliconslopes** [comment]
Worked with Boston and Em to re-write this. Change it to say: 

Pitching at StartMadness will expose your startup to thousands and give you a shot at a quarter of a million dollars. This could be the chance you’ve been looking for. Don’t wait to take it.
