### ISSUE TITLE
Reach out to our customer support team - where do you reach out to??

### ISSUE THREAD

**Issue by emmasiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#31]
![image](https://user-images.githubusercontent.com/82678744/116483714-da618a00-a844-11eb-8490-d9fcfe0e4de5.png)

There aren't any links that I can find for how to reach out to the customer support team, do we even have one? Is it just a SS email? We need to take this off or link a way to contact "customer support".

**Comment by RobertUpchurch** [comment]
Let me know if you want it removed or an email added

**Comment by RobertUpchurch** [comment]
We updated it
