### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by bostonsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#38]
I am not entirely sure what we can replace the favicon with, because I am not sure which would look best. But we do the 2 options, either just the ceo.com modified logo or the ceo.com logo with founder's hub circling it

**Comment by uteinthecity** [comment]
@bostonsiliconslopes what are you referring to?  The logo in footer?

**Comment by uteinthecity** [comment]
@bostonsiliconslopes @demitrih
Let's use this logo for the favicon: https://hyperquake.app.box.com/s/6bel3py2cpj2tplymp0mou5ed3lwzo8m/file/797499601955
