### ISSUE TITLE
StartMadness Page

### ISSUE THREAD

**Issue by demitrih** [AxiaLabs/SiliconSlopes-IssueTracker#41]
![image](https://user-images.githubusercontent.com/34491406/116579640-d0d13400-a8cf-11eb-8228-1c54a37deb37.png)
Slight change to verbage on this page. Add "sign up for" h1. Add "compete for 250k. sponsored by pelion" in h2. 

![image](https://user-images.githubusercontent.com/34491406/116580105-4b9a4f00-a8d0-11eb-953f-bbc1423c713b.png)
I see that this is flexing to the height to match the image. If it's easy to do, can we reduce the space between "start madness Stats" and the paragraph below? Would adding more padding to the top of start madness stats push it down more?

**Comment by RobertUpchurch** [comment]
haha i literally remove the sign up for this morning because it was removed from the figma when i was updateing the pelion thing. I'll put it back after we launch.

**Comment by demitrih** [comment]
yea I removed it in the design ;) they wanted it back.

**Comment by bostonsiliconslopes** [comment]
Sorry for the confusion @RobertUpchurch, it looks like we are just missing the change of the "Compete for $250k Sponsored by Pelion" (The change of adding sponsored by as well as style)

**Comment by RobertUpchurch** [comment]
@demitrih this design is pretty unnatural for HTML its going to be near impossible to make it seem seamless between the SVG and the text. Can we talk about it?

**Comment by demitrih** [comment]
What design are you referring to? The Pelion logo? 

Just change Pelion to text instead of a SVG. Make all the text on that line size 36 font, color dark purple, wrap PELION in a span tag and set it to font family: times, and then add "tracking-widest" to the span tag.

**Comment by RobertUpchurch** [comment]
Haha thats exactly what i did but i was going to talk to you on the phone first to make sure it was ok to imitate the logo. Sounds good. No need for a call
