### ISSUE TITLE
Form Error When Submitting

### ISSUE THREAD

**Issue by bostonsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#42]
When running through the form and filling it out, I am getting an error preventing it from submitting. I checked and all the boxes are filled in. Not sure what I am missing

Screen recording - https://share.getcloudapp.com/QwuEwLlO

**Comment by RobertUpchurch** [comment]
This is a known error. Check the slack on omnicore-system

**Comment by bostonsiliconslopes** [comment]
Sorry I thought it was resolved, my bad
