### ISSUE TITLE
HOF Application Accounts with no SuppDataResults

### ISSUE THREAD

**Issue by Tracey-Omni** [AxiaLabs/SiliconSlopes-IssueTracker#48]
I have identified and corrected 14 HOF Applications Accounts that had no SuppDataResults. CreateOrder was successful but there was no subsequent CreateSuppDataResults API sent. I don't know the circumstances under which this happens other than there are 2 from today that also need to be corrected. We need to find a way to prevent this from happening, maybe by immediately submitting CreateSuppDataResults with the dummy/default TagText and then when the applicant actually submits the real information send UpdateSuppDataResults.

**Comment by RobertUpchurch** [comment]
If the user does not immedietely fill out the form after paying, the site does not create the supp data, however this does not mean that the user cannot continue the application from their orders page. 

We created it in a way that the front end determines whether it should create or update at the moment of saving regardless of where you are at in the app. It uses the same component. There should be no need for you to be manually making them

**Comment by Tracey-Omni** [comment]
Is there somewhere I can test this and verify it is working as you describe?

**Comment by RobertUpchurch** [comment]
Let me see if we can set up a permanent develop branch

**Comment by Tracey-Omni** [comment]
We really need this and I keep forgetting to bring it up in meetings. Our team needs a way to quickly test new code in our Test database. A permanent dev website is just what we need. Thank you!!

**Comment by RobertUpchurch** [comment]
I asked Boston to set up the web url. Should be done by the end if the day

**Comment by RobertUpchurch** [comment]
This is complete. The dev site is at develop.siliconslopes.com
