### ISSUE TITLE
Summit site updates

### ISSUE THREAD

**Issue by brifrancom** [AxiaLabs/SiliconSlopes-IssueTracker#52]
this is not a super urgent task, but we want to update the Summit site until we have more info and content for Summit 2022. [Here](https://docs.google.com/document/d/1fqDXBZoajnB4VY2ka18x6KcxqzL571KpwxhTf6M_KCk/edit) are the changes we’ve outlined - please let me know if you have any questions. Thanks!

**Comment by RobertUpchurch** [comment]
Just a heads up: We are starting on this work today and @joshuackeller will be heading up these changes. Please comment here if more changes come to mind
