### ISSUE TITLE
Add 3 More Categories

### ISSUE THREAD

**Issue by emmasiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#53]
Please add these three award categories: 

Individual Awards
- Business Influencer of the Year :  In a world full of too many influencers, the Business Influencer of the Year is that person that we all truly want to be or be friends with. 

Company Awards
- Service:  The absolute best in class service or services based company. 
- Web3: The best in blockchain/decentralized applications or entertainment.

**Comment by RobertUpchurch** [comment]
Closing this because this will automatically filter into our website once omnicore adds them to the DB. If theres a bug we can reopen it
