### ISSUE TITLE
Editing Team Members: Need Ability to Remove

### ISSUE THREAD

**Issue by DevOpsOmnicore** [AxiaLabs/SiliconSlopes-IssueTracker#55]
Two items:

![image](https://user-images.githubusercontent.com/96309220/146583035-6eeccb0a-4d73-4817-b5ca-9714fe5fec1b.png)

1.  Administrators need the capability to Remove Team Members (terminate Assigned Member Permissions)
2.  Please consider changing the [ Cancel ] button on the pop-out form to [ Close ].

**Comment by RobertUpchurch** [comment]
We can do this. Can you link the API Doc file in this thread of what to call for remove

**Comment by DevOpsOmnicore** [comment]
"DeleteEntityAssignedMembers"
https://drive.google.com/file/d/14HyQDNWpb1lhixW7NmH-CVo3zwryIHDf/view?usp=sharing

**Comment by RobertUpchurch** [comment]
@jaredbawden where are we at with this?

**Comment by jaredbawden** [comment]
@RobertUpchurch It's about done. I just need to make a few small changes. I'll post a PR when it's finished.
