### ISSUE TITLE
Sponsor page not refreshing

### ISSUE THREAD

**Issue by tscertsys** [AxiaLabs/SiliconSlopes-IssueTracker#60]
SS has requested numerous edits and additions to the sponsorship account records. After completing them, I refresh the page (https://siliconslopes.com/sponsors) and do not see the updates and additions I have made. When I check the API log I don't see that ReadAccountsOwnedPublicList is getting sent when I refresh the page. Please advise.

**Comment by RobertUpchurch** [comment]
there is a caching system that refreshes those calls every 24hours believe
