### ISSUE TITLE
Phone Number Does Not Show on Account Info

### ISSUE THREAD

**Issue by bostonsiliconslopes** [AxiaLabs/SiliconSlopes-IssueTracker#9]
On the Account Info Page, it does not show my phone number associated to my account. Nor can I add it or change it.

**Comment by RobertUpchurch** [comment]
Blocked because we do not have readUserDetails up yet.

**Comment by emsiliconslopes** [comment]
My phone number shows up on the account page but there is no way to edit it

**Comment by RobertUpchurch** [comment]
Yes the API doesnt support editing at this time. It will have the phone number in there if you created and account and are using the same browser that saved your login. If you sign out and back in, phone number will be gone until the API updates
